# Generated by Django 4.2.2 on 2023-06-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonApp', '0002_alter_menu_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('guest', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
